on:
  push:
    branches:
      - customdev

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    environment: customdev
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ vars.SERVER }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: /${{ vars.SERVER_DIR }}/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*/**
            **/node_modules/**
            **/.next/**
            **/*.logs*/**
            **/*.zip**/

      - name: Restart PM2 App
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ vars.SERVER }}
          username: ${{ vars.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          port: 22
          script: |
            cd ./public_html/${{ vars.SERVER_DIR }}/
            export NODE_OPTIONS="--max_old_space_size=8192"
            export CI=false
            export NEXT_PUBLIC_GOOGLE_CLIENT_ID_PROD="${{ vars.NEXT_PUBLIC_GOOGLE_CLIENT_ID_PROD }}"
            export NEXT_PUBLIC_GOOGLE_CLIENT_ID_DEV="${{ vars.NEXT_PUBLIC_GOOGLE_CLIENT_ID_DEV }}"
            npm install --legacy-peer-deps
            npm run build
            pm2 reload ecosystem.config.js --update-env || pm2 start ecosystem.config.js
            pm2 save

  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    environment: customdev
    needs: web-deploy
    steps:
      - name: Check the deployed service URLs
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ vars.DEPLOYMENT_URL }}
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
